### ISSUE TITLE
Feature Request:Disable GDKP limit on taiwan server

### ISSUE THREAD

**Issue by takaqiao** [papa-smurf/Gargul#100]
```
        local accountInfo = C_BattleNet.GetAccountInfoByGUID(UnitGUID("player"))
        if accountInfo then
            local realmID = accountInfo.gameAccountInfo.realmID
        if realmID == 5845 then
            self.GDKPIsAllowed = true;
        end
```
not sure how to get other realmids,probably there will be a better solution :)

**Comment by papa-smurf** [comment]
Hi @takaqiao, what's your request?

As far as I'm aware GDKPs are not allowed during this phase of Season of Discovery regardless of which realm you play on. If that's not the case then I'm going to require a source

**Comment by takaqiao** [comment]
> Hi @takaqiao, what's your request?
> 
> As far as I'm aware GDKPs are not allowed during this phase of Season of Discovery regardless of which realm you play on. If that's not the case then I'm going to require a source

Sure Blue post on taiwan blizzard forum :https://tw.forums.blizzard.com/zh/wow/t/%E3%80%8C%E9%87%91%E5%B9%A3%E4%BD%BF%E7%94%A8%E9%99%90%E5%88%B6%E6%94%BF%E7%AD%96%E3%80%8D%EF%BC%88gdkp%EF%BC%89%E4%B8%8D%E9%81%A9%E7%94%A8%E6%96%BC%E5%8F%B0%E7%81%A3%E4%BC%BA%E6%9C%8D%E5%99%A8/12240

**Comment by papa-smurf** [comment]
See https://github.com/papa-smurf/Gargul/commit/1ec4bc8188a8948c84518e0b0f153289a2aa6fa2

Can be downloaded now and will be released on Tuesday assuming Blizzard doesn't change its mind

**Comment by takaqiao** [comment]
![image](https://github.com/papa-smurf/Gargul/assets/13859193/9ea12de0-e12d-45a5-a7a1-5c9688c931cb)

**Comment by papa-smurf** [comment]
@takaqiao your suggested change implies that there's only one Taiwanese realm (5845). According to realm status there are four seasonal realms in Taiwan.

![image](https://github.com/papa-smurf/Gargul/assets/4224975/ebb918eb-0b86-4658-9eb2-7c5ef37b49e0)

Since I can't just change my region to TW (as far as I'm aware) I'm in a bit of a pickle seeing how I can't test any of this nor can I confirm that 5845 is indeed a TW realm.

**Comment by takaqiao** [comment]
> @takaqiao your suggested change implies that there's only one Taiwanese realm (5845). According to realm status there are four seasonal realms in Taiwan.
> 
> ![image](https://private-user-images.githubusercontent.com/4224975/309553931-ebb918eb-0b86-4658-9eb2-7c5ef37b49e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTkxNjEsIm5iZiI6MTcwOTUxODg2MSwicGF0aCI6Ii80MjI0OTc1LzMwOTU1MzkzMS1lYmI5MThlYi0wYjg2LTQ2NTgtOWViMi03YzVlZjM3YjQ5ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDIyMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjOTZhZDljMzkxNTc3ODY0Yzc4Njc0NmZhYjA0OTU3OWNjZTAwNjg3MjE1MDQ5OGEwNzA1MWVkMDM0NWE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WmC0wjsWZyA0y-5HKiTf-_qE00vOdOZH3yLmkkFnfSA)
> 
> Since I can't just change my region to TW (as far as I'm aware) I'm in a bit of a pickle seeing how I can't test any of this nor can I confirm that 5845 is indeed a TW realm.

I see.Thats why I create this issue,cuz I can only test one realm,I also cant able to test other realms(there are two realms r locked right now)

**Comment by takaqiao** [comment]
> @takaqiao your suggested change implies that there's only one Taiwanese realm (5845). According to realm status there are four seasonal realms in Taiwan.
> 
> ![image](https://private-user-images.githubusercontent.com/4224975/309553931-ebb918eb-0b86-4658-9eb2-7c5ef37b49e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTkxNjEsIm5iZiI6MTcwOTUxODg2MSwicGF0aCI6Ii80MjI0OTc1LzMwOTU1MzkzMS1lYmI5MThlYi0wYjg2LTQ2NTgtOWViMi03YzVlZjM3YjQ5ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDIyMTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTFjOTZhZDljMzkxNTc3ODY0Yzc4Njc0NmZhYjA0OTU3OWNjZTAwNjg3MjE1MDQ5OGEwNzA1MWVkMDM0NWE2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WmC0wjsWZyA0y-5HKiTf-_qE00vOdOZH3yLmkkFnfSA)
> 
> Since I can't just change my region to TW (as far as I'm aware) I'm in a bit of a pickle seeing how I can't test any of this nor can I confirm that 5845 is indeed a TW realm.

I got a new idea using local realmName = GetRealmName(),
![image](https://github.com/papa-smurf/Gargul/assets/13859193/8a8ee3ba-d9a3-4c26-b971-846518fcbf75)
I just tested,seems like this one working prefect

**Comment by papa-smurf** [comment]
Is it possible to temporarily set your client to English and see if you still get these same realm names or whether you get an English variant? If you still get simplified Chinese then this will be an easy fix. Thanks!

**Comment by takaqiao** [comment]
> Is it possible to temporarily set your client to English and see if you still get these same realm names or whether you get an English variant? If you still get simplified Chinese then this will be an easy fix. Thanks!

![image](https://github.com/papa-smurf/Gargul/assets/13859193/4c973517-51c8-4b3f-91be-9d077488203c)result is same:D

**Comment by papa-smurf** [comment]
Good to hear. Then it should work with

```lua
-- GDKPs are not allowed in SoD Season 2
if (C_Seasons.GetActiveSeason() == 2
    -- Taiwan is excluded apparently: https://tw.forums.blizzard.com/zh/wow/t/gdkp/12240
    and not GL:inTable({ "十字軍聖擊", "孤狼", "生命烈焰", "野性痊癒" }, GetRealmName())
) then
    self.GDKPIsAllowed = false;
end
```

**Comment by takaqiao** [comment]
> Good to hear. Then it should work with
> 
> ```lua
> -- GDKPs are not allowed in SoD Season 2
> if (C_Seasons.GetActiveSeason() == 2
>     -- Taiwan is excluded apparently: https://tw.forums.blizzard.com/zh/wow/t/gdkp/12240
>     and not GL:inTable({ "十字軍聖擊", "孤狼", "生命烈焰", "野性痊癒" }, GetRealmName())
> ) then
>     self.GDKPIsAllowed = false;
> end
> ```

Appreciated:)
