### ISSUE TITLE
Not able to bid with minimum button

### ISSUE THREAD

**Issue by Quikx123** [papa-smurf/Gargul#101]
Hi,
I have an issue were hitting Minimum button does nothing. It works for everyone else in the raid but me.
Addon is updated and I reset settings to standard. Reinstalled addon, etc.
Any issue were the issue could be? Or what information is required to figure it out?

Thanks

**Comment by papa-smurf** [comment]
Hi,

Can you provide your `/gl bug` output please?

**Comment by Quikx123** [comment]
eJylWVtzIrcS/itkzkNeMIerMZuXHS62qQVDmNklqVTKJc8IUDxIRKOxTbb2v59uSXMFHFedl2Td3dK0ur/+uiW+O24YCj4mijifvjs/DZPtnSRPT1Q6n/5wXlrNRrvRceobEsX0z7rjqojERtPotRvNG6euZJJpZkKoEfw/ZoE26sDq5kWTx5GIIhooJnj8IXNJNorx7UdszYE+YJfwLYXvuzxcERZ+yI9b8nGfF4cPmy5flpfMHq3NWqwLwe9VjOxZZiIopqibWQ3JdiiF2unc8iSKCgouOK7R+W4NnLIGEsU3bHt21eNdwqJwSPhzVS3FM5WPy4gcaeizPc327xWOB3jzSPB8FmyjiAXPcyEPO7200UelXZfrbKaLnwbl3wm1wew1rq8kjSiJabZ6PJxfuZsNe6NxZanW/EMxTGc0Q0leIyrPLRoJqb/YvqGb/tNT6VPj+e2ZFWNJtoJP40g7gaGB8zdLC+++Ti/tuUgg59wA9qnZ7gdht6TXaL4ajt7XfyOcRRF532gt/NkXNBl0yVOnE5RMPEVUEg+JxBTryJx199vy22Su9+g3e09hWFaSJFJiA8ic8oBITtRpXmiQyJi9mBgDFFrXOVDG9C9iKwTd0U50mt1mR7by71BFWKRV/7H/hmi3u812a9BotTudZqPV61XNAfn7A5G0feKOUSP4PCUgk/SCxYQHIuGKytyBc2YY6dGOBtUqSvWekpTsTyo3VfuMH/0dmKgLBpDobUJkWFFP+I7wgGruu5XwARM7CEijncf3Vvz1F0sB3irR0934yzK0axp5+O6I3CYRyqFoC+b3LAQCB7TY4uw22tenygprloymiu5XljE6jX7/RJGvLR50BqGR7A3oKLFHhHzftLPV85WP4u5NOz/EnBxiZRphqwHlmTe7uXihvhCRYocZUzYszcI558c4Ekr732u0IDaZ5kG8kCmPFYbdl+Bv+oFeTm6LPWcjXbk3ENVWRX6ejZckio5L8Zo2buC9/lVge3FmlJHxnHG2J4dRJEwo0T4P8lISdYV505EaNLr9E9XjjD1JItlJpf6a0FgxHRNYWNh09dsSekVoIPbShQ+2bnKMraDKvIBwbg6AWe8UAOXtQB/OachIirbWVWswOGfwOD+mhkXHvAOl4dFNlMCu62geaWseSQ2AO2Ziq2eX4kKfBMJnB1zRRLeyBT4LjxBSYKtHU3zmDx1P8K/Ryd1bU/LsJtIMTz1EU+tU58pgZynukslchDRaErV7d6NC/Vwy8en+kHl7anQQ3HuFatSsXkBimq71DngW8AswMgMZNPVi716LV4/t48nbQUhbQ+1CAZHk7Yrg4GlLvF3ACSu0/KJXRv5A1akq4UzFAB67W6uRFvYPqHxBwox7v+NRYeGnVr85ANIf9K7rIEJGK4n6iIy+lt0MrtvNZrNumaxkBuWlcH8aLrjRdFrXN902fNYLJDuoiZQCm6ID1OB4VOH4qt1wX4GM4Q8Dxe8OAB/aREC1fE7jGDpKPOV6uBrtkNZ1ZOuXDFfr3AIQ7kLZb7m7gdCnX3I5MqTzCeNijCB9If2IzZjFlAfQKXQmK8ophx75hB5aRdGxCSdPEQ1LugVf0YBqnKcel8SampL9rwmJmDo6n7p1J35mB+2jpj65JwjvMSOR2NpNIOJDIYCuwxVcKnSI0UO0DJAZ3SCgB4Xt+lYKOKHj1MsGmj/MLGl8DekGx5IRbAqpbWaCpWAcR4xWM5d5ih6MEdUHXu9YfKASArOHGS3dkabBsMfG+TN114qAHrliG4ZxdoYrcPIgmZA6Dq26I2lMJbQeIJt4JyLYqnXThKOPpTgcaFgFU0FcRojVo8IXBl7GxX0p9ouNay3t1t1TCyDMbaYGV0zFF5AdJDGE+VZg1uBQn6fjXz6PXX9S++xP55NfPq+nDw8TPGlYQNm0GIfHggYGR2dj94KAMB5ESQmgISI4Ts9j9YvNBvIRlFQQwFf00ZTKHr63onC4MIX4DzPc4BFw3Yy+0Cif4bDHQ+KZm+i7oIm6Yh5nB8B1q2dB/SAAXrTijUZyAQdWPFxMqn7PgaAlwDwHiA3/LUztxQJR+n513UQwpDSzhDDqakZnicb/EMb5Gc4IPsTK1lmOijAEFxAzsS+giyeZ36C5IL4DEPqGB9YQO/Ga6VKaMvGB1ipVVYfewAASF/jBakY4MsNu3MC2rLxlnEQjqNmq4oG+wpbnpec2WkLyNfulOUzV5Twa7YSHM0pfCcS7bTkW0/iNEbuc5tz4xEKAkY4VzLT0K09irPws0kYP0w7KAMUBBiHfZsH11pm5qSBTWIU68ifzuq2e+ue7xWwMfy3W9xN37JTX3FOiUa1xXNczoKxj5urQpXegjBjc3tM1EJXqp5Yz93f8yOirf2qW7W43HiXKyYgR7nOSYm2V+dJCT2erZ+SweEjVK6Vcxy204Yh1gIAAMIBak9eC4dNhHuyMaEv+t5BpLWTMOwQSNeMvUD4hYtCXDDhMunnezTbA1dsMHTZbnaatQfZPKWMlgNsixZopFikHMtgcpxv4JlweZnmx8GT/BJtsbqH7eTQQcK0HWk5rwMAwtTmnB7VIFKDKAxmE1F6/PtWS3ZXYYROp5rSFjYUGLNa4hzP9jfGbxvckUnk5/l3MxIPAWLm2VBzvy3TpGBYFebn4UXjPACXyuOD2nlTU6WRVloBx2vldHma4yUjMmBmewyS8mhaLMM5Y2dK2bmtISemTxHd8jCJhQGLTkXZ4zYiKDcRSsm0QZV4+01zKBveIQH5WhR7M6CZHBnnDE2beGV2r3aw2VgMYm3O7dRvZnZYnqh077ScFmS88Gm1KmuJx8rZi/HqwH4Q7eKxh9Y6/cUZfOt1CPdNjuYMazYJHx/WO8jnByzTmRt8YbK4qUuiiEXBs/DWmY0MV0EHpyeCSYX/Bg1Ntvid68o7STqnIjD/va0kMLtTUjtZM+dT0BaWmRA3oR0n2lChai2BhozaGT0eAqBpTNbapHUVSA9OfVe0Vwoor9iyOa1CTNdhA4oT3k5O7gCPfhJ80KhSX+yQ0mcWhGDkq06HXWFg6xZUw4phQOf/FD9ZgSKrNvRr81/w9GGjRwkNyLpKH5TpoAQ9IDhFU3z1O8HDRLEP6XxgI+GRDJd7BiyktjKp4K7LPDsNEKTM0uSnLwz9n/uNoNh19gTOMp547nE2wk6F4Ph2PZ5MLytX07t6/oPPup7cXdzXKd/c2Jpe+kIru3NXd1xkK/NXs3Ne0/OKHtPbiN1B58RgF7fvbv3+Q8lp37a7G91PPX6x+B2Vp0XS+XKxwCii75C1u/dXEy+QXnTnjx+Q3vWWV237gm1bwDFM2RXSsEvNO/mdeMBenfiwce1O8kyI5lK7GVuGJSJTkYzNjQIfUa8z1xc4Txq+yqjSEoC7HfaZEtrjT4LeNnlJolWoHzIDXjljlt1d8mFxw+v/dXNP5El/1TsWX76bwfeQQ/R5peXio3yb1W/ofzhwy26rjBNc2LzzpO88fzkKrBoN6R7+4WAVkKYZxY3j0xAbuVfmlSwv9+XAJ19oT4ZrFu0hHxXZ79MHFQT+NEnppHTRDM87vKMwOWW5LlhmLswbekHbwxSBRX+jRxjudagpIJWYGP6GRbBrFpjaazad6Jiq8ZuS3VVh9Ur7Ivgms1j9g2atTel4BrXLKy5CV5gRl36xwkV9dCuxpr7Z0SwvpzfKQvw5M+UZMefH2X9Tg6bJoF8vAznNxWXr+xWPD3syt4MH8tJDPLPiJxWZJxSGiD/g8YU9t3QUwoKsL756YC+syewYpu4pyhMwFl1OzFFmXzN6vp39z2FjgN2b2G9NN6vA0XuKrDc+CbCdD1GfWXD9EWF/3p8alrS8aV4a4osmEK/NU3zsxs/nMLDo9BBCEAFKqqClHx4LKGmEEDX/mY15B9RUHKTxfp2iADK2DyKsIQm0xHOct8CeqUsxRWAxMdRnCSL9wFuIQ5yNmKp6YWrXaFNOZ7A5Km5+R28fKDOpboPmSLQqqRgy7VMlKS6pm//IKh5cFgazhwG3/4XHuev5kNVss4L/YRdOx0dbiPY2ykKH3WzorDpBPyRZHvUn1bVJw5cEdF5i0hfDeQvlsdwonw5V5hCy33MxiftRynPoL9WOVabVeWmxZ6p3t00K+pK++OHORPkXnc6zQ1+RccJBiwyIqqzFAgH09hERRF7R5V49x+Si9RDre7W9QHq80CsSeZlcKi8AgYrpC9c/REG/8vZjpS4v+taDd710PACsJvoTYF5Srbrffv2r2uh134l7D1pzgpRd/4WPPb8j+lEQ4CHyjXLyx2Pnxv6BAMBU=

**Comment by papa-smurf** [comment]
Try again after disabling iMorph. Also don't forget that usage of iMorph is banable :)

**Comment by Quikx123** [comment]
Will try next raid. You know why this causes an error? Haven't had issues with it before and was using both for quite some time now.

**Comment by papa-smurf** [comment]
Not sure, it probably does something with buttons. If someone wants to look into why it happens and come up with a solution then I'm open for a PR!

**Comment by Quikx123** [comment]
will let you know tomorrow after raid if it fixed the issue. thanks

**Comment by papa-smurf** [comment]
Will mark as fixed for now, get back to me if it was not fixed
