### ISSUE TITLE
Randomly awarding loot gives +1

### ISSUE THREAD

**Issue by tylerhagan** [papa-smurf/Gargul#102]
The way we're awarding loot that no one rolls on is by awarding (alt-shit-click) it and having gargul assigning it to a random player.

However unless i'm missing something obvious; this always gives that randomly assigned player the item as a +1.

Could we have a setting to turn this off/have this turned off by default?

(I'm referring to the version used for classic/classic-sod)

**Comment by papa-smurf** [comment]
Fixed the issue and will deploy it next Tuesday, thanks for reporting!

This is basically the result of the random award popup "memorizing" the +1 checkbox status of the normal award popup, so if you award something with a +1 and then award something to a random person that +1 will carry over.
