### ISSUE TITLE
Option to use +1s to sort roll off. 

### ISSUE THREAD

**Issue by silvabrios** [papa-smurf/Gargul#109]
I don't see any option for this, but would help the Loot Master when using +1s as sort of a round robin, say if someone with 0 rolls a 1 but someone with a +1 rolls a 99, the 1 roller will get the item. Being able to influence the sorting by +1 counts of roll offs would help the Loot master in these scenarios.

**Comment by papa-smurf** [comment]
This feature is added with v7.5.12, Default is `Ascending`

![image](https://github.com/user-attachments/assets/fca5147b-0bd4-4018-b7ce-7a2c9bee899f)
