### ISSUE TITLE
LUA error when trying to announce TMB prio in chat. (Including fix)

### ISSUE THREAD

**Issue by TheClarkster** [papa-smurf/Gargul#110]
In TMB:announceDetailsOfItemInChat (TMB.lua line 1574) playerName is not being initialized, causing a crash when displaying the chat output.

I added this line to line 1602 in TMB.lua:
local playerName = Entry.character:lower();

Because I saw that you used that in the other functions, like the tooltip code.

Everything then works again.

**Comment by papa-smurf** [comment]
Hey @TheClarkster , appreciate the reportI very recently fixed this and will release it later today :)
