### ISSUE TITLE
Retail: User.lua:320 Error

### ISSUE THREAD

**Issue by evilgodly** [papa-smurf/Gargul#113]
I am getting this each time i zone in to a Delves in Retail.

176x Gargul/Classes/User.lua:320: bad argument #1 to 'lower' (string expected, got nil)
[string "=[C]"]: in function `lower'
[string "@Gargul/Classes/User.lua"]:320: in function `groupMembers'
[string "@Gargul/Classes/User.lua"]:413: in function `groupMemberNames'
[string "@Gargul/Classes/SoftRes.lua"]:628: in function <Gargul/Classes/SoftRes.lua:612>
[string "=(tail call)"]: ?
[string "@Gargul/Classes/SoftRes.lua"]:751: in function `tooltipLines'
[string "@Gargul/bootstrap.lua"]:352: in function <Gargul/bootstrap.lua:323>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
...
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Pawn/Pawn.lua"]:2143: in function `PawnGetStatsFromTooltipWithMethod'
[string "@Pawn/Pawn.lua"]:1384: in function `PawnGetItemData'
[string "@Pawn/Pawn.lua"]:6009: in function <Pawn/Pawn.lua:6000>
[string "@Pawn/Pawn.lua"]:5992: in function `PawnShouldItemLinkHaveUpgradeArrow'
[string "@BagBrother/core/classes/item.lua"]:316: in function `IsUpgrade'
[string "@BagBrother/core/classes/item.lua"]:237: in function `func'
[string "@BagBrother/libs/MutexDelay-1.0-2/MutexDelay-1.0.lua"]:36: in function <...ns/BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:30>

Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by papa-smurf** [comment]
Hey @evilgodly. According to the API docs this should not be possible and might very well be a bug on Blizzard's end. 

I've added a temporary workaround in Gargul for now, thanks for the report!
