### ISSUE TITLE
In Classic Era, Trade Announce doesn't seem to be grouping items correctly

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#118]
Should say, "I gave Sweet Nectar, Moonberry Juice x41." Instead it's listing Moonberry juice twice. 

<img width="423" alt="image" src="https://github.com/user-attachments/assets/0af2b2c9-e335-4385-adba-d214dbd16a1a">

**Comment by papa-smurf** [comment]
This should be fixed in tonight's release, thanks for reporting
