### ISSUE TITLE
[Enhancement] +1 Export Formatting

### ISSUE THREAD

**Issue by brentrichardjr** [papa-smurf/Gargul#119]
I currently use the +1 feature in retail and post the export into either the Raid chat or as a note in MRT. It is more than adequate for my needs (as the tracking is the biggest hurdle), but visually, I don't like how the text is formatted on export. If posted to raid chat, it can be hard to read as everything is lowercase and there are no spaces. It is better in a MRT note as the new lines are preserved.

As an enhancement, I'd like the current export format modified or an option to select custom or additional formats.

When posted in raid chat, the current export appears like such:
character1-server,0charcter2-server,1character3-server,1

And in an MRT note (with breaks preserved):
character1-server,0
charcter2-server,1
character3-server,1

A modified export in raid chat could be:
Character1-Server: 0; Character2-Server: 1; Character3-Server: 1;

And in an MRT note it would appear as:
Character1-Server: 0; 
Character2-Server: 1; 
Character3-Server: 1;

For a custom or additional export, I envision maybe an MRT export that color codes the class:
|cffaad372Hunter|r-Server: 1
|cfff48cbaPaladin|r-Server: 2
|cff0070ddShaman|r-Server: 0

**Comment by papa-smurf** [comment]
The export format is meant to be imported again or be used in an external datasource. It was never meant to be used for display purposes. If I change the export format, I need to add an additional import format, with more options resulting in having to write and maintain more importers.

+1 values are synced across players, so let them they can use `/gl +1` to see the numbers

Alternatively they can also whisper you, either for themselves or for others:
![image](https://github.com/user-attachments/assets/8a25d630-4716-40d4-80d9-a2a94b66ee20)
