### ISSUE TITLE
Show details in tooltip

### ISSUE THREAD

**Issue by JakeFanelli** [papa-smurf/Gargul#13]
Currently the details only show up in mouseover tooltips like so
![image](https://user-images.githubusercontent.com/31941477/152400630-c7107609-6bed-4a96-9652-3d9446ec020c.png)

When I click on an item in chat, the details are not there, can these be added?
![image](https://user-images.githubusercontent.com/31941477/152400735-9667a6a1-468e-45a5-b5eb-df2e2305bfb6.png)

**Comment by papa-smurf** [comment]
Thanks for the report @JakeFanelli , this is a known "issue" (not really an issue, but it's understandable you bring it up).

If you're curious about what's on the roadmap be sure to check out our discord as well :) https://discord.gg/D3mDhYPVzf
