### ISSUE TITLE
Round Robin for PackMule

### ISSUE THREAD

**Issue by kasperlandgren** [papa-smurf/Gargul#14]
It would be nice if I could input flask users (secondary request) and distribute Mark of the Illidari in a round robin fashion (primary request) rather than purely at random.

**Comment by papa-smurf** [comment]
Hey Kasper thanks for reaching out. I haven't built in round robin (yet) because it's a lot of effort for a very niche use case. I'll put it on the list, but it won't be high op in terms of priority :)
