### ISSUE TITLE
Addon trades arbitrary items instead of the one selected

### ISSUE THREAD

**Issue by BjarkeM** [papa-smurf/Gargul#17]
When awarding an item, the specific stack selected should ideally be used. I noticed when awarding things that can stack (hearts/gems/enchanting mats) it will not automatically trade the specific stack selected, it will find the first one in the bags.
Even if it's a 20 stack, instead of the single material you awarded!

**Comment by papa-smurf** [comment]
Valid concern, thanks! It's not something I've ever run into, but with heart and other mats being rolled out in some runs I can see where you're coming from. I'll add it to the roadmap and will determine the priority based on the effort involved. If you ever want a status update feel free to drop by on our discord! :)

**Comment by BjarkeM** [comment]
Fatfingered the close issue button - sorry!

I suggest you add a readme to the repository with a discord link (or any other relevant info).
if I get the time, I will look at adding it as a feature myself, but I'm not very familiar with the wow LUA api and if it's possible to easily separate stacks (e.g. if someone awards 2x of an item and sorts their bags to merge stacks before performing a trade.. you could store the amount alongside the item and separate the stack instead of storing locations)

**Comment by papa-smurf** [comment]
There's a wiki, with the discord link being the first thing mentioned. It's almost mentioned on CurseForge and in the add-on :)

It's possible, but since items within your bags don't have a unique identifier it's a bit more work.

**Comment by papa-smurf** [comment]
Added this to the todo-list :)
