### ISSUE TITLE
Remove the <Gargul>

### ISSUE THREAD

**Issue by Graxo** [papa-smurf/Gargul#19]
Is there a way to remove the <Gargul> text from the annoucements? This is just not needed when giving out loot, makes the message unnecessary longer.. i get you want credits for your addon, but i get messages why its there in the first place and that its a bit annoying.

**Comment by papa-smurf** [comment]
Hi @Graxo, appreciate the feedback. Feel free to check out our Discord for the reasoning behind these decisions! https://discord.gg/D3mDhYPVzf

**Comment by Gogo1951** [comment]
> Is there a way to remove the text from the annoucements? This is just not needed when giving out loot, makes the message unnecessary longer.. i get you want credits for your addon, but i get messages why its there in the first place and that its a bit annoying.

@Graxo ,

Not my project, but the only way add-on creators can get the word out is when people help promote, or when their own add-on helps promote. Not having some sort of branding would be doing a disservice to the creator's ability to spread adoption. It's why you see Questie, and others do this. It's just smart branding.
