### ISSUE TITLE
Request for Trade Announce

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#20]
It would be nice to have an automated trade announce.

/raid Gargul : I gave X to Sam.
/raid Gargul : I received 5,432 Gold from Sam

/raid Gargul : I gave Runecloth x 60, [Some Green], and...
/raid Gargul : ... [Some Other Green] to Sam

/raid Gargul : I received [Enchant] From Sam

/raid Gargul : I received [Lock Pick] From Sam

(Since the list can be longer than 255 characters sometimes you have to split it into multiple messages.)

That sort of thing.

Asking because it's one of the things that GogoLoot did and some of my old users were asking about this with Gargul. It comes in handy for GDKPs / speed runs where you want to keep everything transparent. GDKPs are only going to increase in popularity during Wrath.

Cheers!

**Comment by papa-smurf** [comment]
Good idea, will add this to the next update since most of these functionalities are already in Gargul (who traded what)!

**Comment by papa-smurf** [comment]
Btw something interesting I found out: a message containing only item links can be longer than 255 characters. Example: https://tbc.wowhead.com/item=31986/merciless-gladiators-crossbow-of-the-phoenix has a itemlink of ~105 characters, but you can still include 5 of these links in chat. 5 seems to be the max for all items, regardless of the length of their name.

How many characters you can include in a message next to those 5 itemlinks depends on the itemname itself. To calculate how many characters you have left you subtract the number of characters of all the items that you included itemlinks for (including their opening and closing brackets [] ) from 255. In the case of 5x Swiftthistle (12 characters + 2 for the brackets each) it would look like this:

255 - 5x14 = 185 characters left
