### ISSUE TITLE
Request for Trade / Gold tracking in CSV Export

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#23]
Your CSV Export would be really helpful for GDKPs. Can you set it up to track how much things sold for too?

I gave Joe X item, Joe Traded me Y Gold.

Would need some edge cases around multiple items being traded at once. But it would be really great to get a CSV out of that at the end of the night.

For that matter, a GDKP auction tool like GDKPd would be nice to incorporate. That would probably make tracking sale prices easier. GDKPd has like 0 real support, just keeps getting hacked and duct taped each expansion. Would be nice if someone put in time to improve UX on that.

**Comment by papa-smurf** [comment]
Will be a part of the GDKP module :)
