### ISSUE TITLE
Request for "Auto Open Items" Functionality

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#25]
Open all the clams!

Another add-on that isn't well maintained. I updated it but I don't really want to keep doing that.

https://www.curseforge.com/wow/addons/auto-open-items

All it does is attempt to open things in your bags.

It'd be good to have an ignore list, and default that list to have things that contain BOP items.

Normally I love more opportunities for branding and such, but I think this should open and only report to the user. No need to know that Gargul opened clams.

Happy to have you take the code and item lists. It's all easy stuff. It shouldn't fire in combat (code already does this), and it shouldn't fire when a vendor is open (code does not currently do this).

This feature would help move towards an "all in one" loot add-on for everyone, and help expand usage of Gargul past just Master Looters.

And it's all easy stuff to build in. (=

**Comment by papa-smurf** [comment]
@Gogo1951 You've been busy! 😄 

I've been meaning to make Gargul more of a full-fledged loot add-on that also works when solo/group looting and not just while master looting. This would be a nifty addition to that so I'll definitely add it to the list!

Heads-up: I maintain Gargul's todo list on our Discord, if you want to see what else is on the list or what I'm currently working on be sure to drop by!

**Comment by Gogo1951** [comment]
You know me and Discord. Never had much luck with it. (=

Trying to trouble shoot that one other bug, I may drop by if I can't figure it out. Cheers!

**Comment by Gogo1951** [comment]
Hey @papa-smurf ,

You can use the list here... with UX similar to #22 .

https://tbc.wowhead.com/items?filter=11:10:2;1:2:2;0:0:0#0-2+19

Suggested items on the ignore list:

(Really short ignore list, not many items contain BoP items.)

https://tbc.wowhead.com/item=9276/pirates-footlocker
https://tbc.wowhead.com/item=20768/oozing-bag
https://tbc.wowhead.com/item=32724/sludge-covered-object
