### ISSUE TITLE
Conflict Issue

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#29]
Got this issue when I installed Gargul.

It'd be good to have a warning when people have conflicting add-ons. I have Loot Window in Elv turned off. Not sure what's causing this.

Seems to be a conflict with TSM or Elv though.

Message: Interface\FrameXML\LootFrame.lua:568: attempt to index local 'colorInfo' (a nil value)
Time: Tue Apr 12 16:10:27 2022
Count: 1
Stack: Interface\FrameXML\LootFrame.lua:568: attempt to index local 'colorInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\FrameXML\LootFrame.lua"]:568: in function <Inte'9rface\FrameXML\LootFrame.lua:563>
[string "=[C]"]: in function `MasterLooterFrame_Show'
[string "@Interface\FrameXML\LootFrame.lua"]:98: in function <Interface\FrameXML\LootFrame.lua:24>
[string "=[C]"]: in function `LootSlot'
[string "Error in: Confirm Loot Roll"]:3: in function <[string "Error in: Confirm Loot Roll"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:611: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:747: in function `ScanEventsInternal'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:854: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:839>

Locals: errMsg = "Interface\FrameXML\LootFrame.lua:568: attempt to index local 'colorInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Gogo1951** [comment]
This came up on my 2nd Kara run... a lot, every time I looted anything.

Let me know if I can help troubleshoot.

Message: Interface\FrameXML\LootFrame.lua:568: attempt to index local 'colorInfo' (a nil value)
Time: Wed Apr 13 00:52:49 2022
Count: 20
Stack: Interface\FrameXML\LootFrame.lua:568: attempt to index local 'colorInfo' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\FrameXML\LootFrame.lua"]:568: in function <Interface\FrameXML\LootFrame.lua:563>
[string "=[C]"]: in function `MasterLooterFrame_Show'
[string "@Interface\FrameXML\LootFrame.lua"]:98: in function <Interface\FrameXML\LootFrame.lua:24>
[string "=[C]"]: in function `LootSlot'
[string "Error in: Confirm Loot Roll"]:3: in function <[string "Error in: Confirm Loot Roll"]:1>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:611: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:537>
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:747: in function `ScanEventsInternal'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:708: in function `ScanEvents'
[string "@Interface\AddOns\WeakAuras\GenericTrigger.lua"]:854: in function <Interface\AddOns\WeakAuras\GenericTrigger.lua:839>

Locals: errMsg = "Interface\FrameXML\LootFrame.lua:568: attempt to index local 'colorInfo' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by papa-smurf** [comment]
People already get a warning when they have conflicting add-ons (Gogo, RCLC etc). As someone who uses TSM and ElvUI as well I can't help but wonder: did you update both of those add-ons? Also: I don't see any indication of Gargul having anything to do with the error messages so I don't have much to go on at this moment. If you have a way for me to reproduce these errors let me know!

**Comment by Gogo1951** [comment]
GogoLoot is gone. 

TSM and ElvUI are latest and greatest.

Elv 2.4.2

TSM 4.11.26

![image](https://user-images.githubusercontent.com/55365231/163202171-6d518c8f-f283-4c2c-96d9-2954aa1a292f.png)

**Comment by papa-smurf** [comment]
Which one specifically? Will add it to my knowledgebase ^^
