### ISSUE TITLE
"Packrat" UX Suggestion

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#30]
This should be a dropdown of everyone in the current raid, not a manually typed name. That would make selection foolproof.

It should also announce on save when it's set or changed so everyone in the raid knows where and why things are going where they go.

It bugged on me when I switched toons, it had the old toon saved there still. That should never happen.

![image](https://user-images.githubusercontent.com/55365231/163062820-c6ef7047-1b68-45df-993b-167fa0fa8658.png)

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/163074109-7385b0e0-4f25-4508-8b0b-3e281afb5840.png)

**Comment by papa-smurf** [comment]
@Gogo1951: It should also announce on save when it's set or changed so everyone in the raid knows where and why things are going where they go.

You could do it for the rarity rules (e.g. blue+ to this person, green and lower to that etc), but announcing EVERYTHING has the potential of overflowing your chat. I personally have like 10 loot rules set up.

In my opinion it also doesn't add anything, and it's something I didn't like in Gogoloot. People can already see the master looter threshold in-game, does it matter who it goes to?

In ZA runs I always say: master looter is on, Amani Hex Stick are sent to a random player. Issue solved ^^. Did the same in ZG: "master looter is on, coins and bijous are distributed randomly".

Also: the bug you refer to is not a bug. Settings are not character-specific. You can use SELF to refer to yourself without having to resort to names :)

**Comment by papa-smurf** [comment]
Another thing to note: dropdowns for names are not an option since it would make compound rules impossible. If you have a workaround for that do let me know :)

Example of a compound rule I use:

Send `Epic` and lower to `!Disenchanter1 !Disenchanter2 !Disenchanter3 SELF`

**Comment by Gogo1951** [comment]
Got it, right at the top.

Nobody reads. (=

"SELF" Easy.

I don't understand the point of the complex rules. It's just a way to say, "It's either Joe, or fallback to Sally, or fallback to Mark." Yeah?

Meh.

May be good to default the value to SELF is all.

**Comment by Gogo1951** [comment]
I'd just add some helper text and switch the order around. Literally I just gloss over text. It's not good UX to make someone read. Set the default to SELF, and have the whole "Read More" at the bottom. I still don't understand the list of users... just seems odd. Like a temp fix. It's for unique items? I don't get the use case. 

![untitled@2x(4)](https://user-images.githubusercontent.com/55365231/163263856-a43b6631-a19a-423c-96ce-2fbf30ed4655.png)
