### ISSUE TITLE
Suggestion Build in Speedy Auto Loot "No Loot Window" Functionality

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#31]
Even with Elv Loot frame turned, off, the "Speedy Auto Loot" hide the loot frame option isn't quite working.

I still see a Loot Frame for a second before it goes away.

![image](https://user-images.githubusercontent.com/55365231/163064782-cad0c2e7-938d-4c41-ad88-6b717a5e66b3.png)

**Comment by papa-smurf** [comment]
I don't have a speedy auto loot, maybe I misunderstand your issue?

**Comment by Gogo1951** [comment]
Try https://www.curseforge.com/wow/addons/speedyautoloot -- it's really nice. Never seeing a loot window is bliss when looting on the fly.
