### ISSUE TITLE
Suggestion Announce for SoftRes.it could use some re-work

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#32]
It says like...

<Gargul> Item
<Gargul> Reserved by X.
<Gargul> Item
<Gargul> Item
<Gargul> Reserved by X.

It should use one line per item. My 2 cents. Gets confusing seeing them split, and having an item in between.

Like...

For items with 1 SR...

<Gargul> [Purple Item] was awarded to X. Congrats!

For items with multiple SR.

<Gargul> [Purple Item] was reserved by X, & Y. Master Looter will handle this item manually.

For items with no SR.

<Gargul> [Purple Item] was not reserved. Master Looter will handle this item manually.

**Comment by papa-smurf** [comment]
Agreed, but a lot of effort for little value which is why it's low on the prio list :)
