### ISSUE TITLE
Suggest GDKP Auction Support

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#34]
GDKPd is the defacto standard for auctions.

However... it's not well supported. Hasn't had an update since 2020. 

It's in dire need of someone who can take it over and re-build it right. 

https://www.curseforge.com/wow/addons/gdkpd-classic

Permissively licensed! (=

**Comment by papa-smurf** [comment]
On the todo list as my next project :)

**Comment by Gogo1951** [comment]
Will that be an extension of Gargul, or a stand alone? Suggest keeping it as an all-in-one for loot.

If everyone has a copy, then you can do auctions in the add-on. Opens up a world of cool stuff you can do. Silent Auctions, 2nd Price Auctions (these totally got our GDKP pot sizes up!) and ample room for behind the scenes auto-bids... people could just put in 500g and it would auto bid for them. Sort of like GDKPd tried to do, but it never really worked very well. GDKPd needed a better in-game UX experience.
