### ISSUE TITLE
Request to Add Void Crystals to Announcement Ignore List

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#39]
![image](https://user-images.githubusercontent.com/55365231/164082458-3cadd358-a9d6-42ad-819a-7d73068ea733.png)

Void Crystals shouldn't show up in chat.

**Comment by papa-smurf** [comment]
Opinion ;)

**Comment by Gogo1951** [comment]
Also, good to check the logic... if you did want to announce an item like this, it'd be good to announce the quantity as well. (=

**Comment by Gogo1951** [comment]
If you want to include the void Crystals, it'd be good to setup logic... similar to looting a corpse...

"Received X from Y" where it outputs the source of the thing you looted. Be it a gem bag, or DE'ing something... or a mob name.
