### ISSUE TITLE
Something is causing the Announce Checkbox to Dissappear

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#42]
![image](https://user-images.githubusercontent.com/55365231/164114471-342abcca-f98d-4a5a-b7f1-7c463e49248b.png)

It sort of comes and goes, no other loot-specific add-ons or weak auras running. 

Elv conflict? Check out the code from GogoLoot on this? We didn't have an issue here.

**Comment by papa-smurf** [comment]
Probably ElvUI related. I don't test ElvUI on everything I make, I usually wait for the user reports. Also: I will always write code myself unless there's a library available :) Not to reinvent the wheel, but mostly to avoid fuss and to make sure I can always stand behind what I made

**Comment by papa-smurf** [comment]
@Gogo1951 can't reproduce this even after 50+ trades using ElvUI, so if you find a way to reproduce this please let me know.

**Comment by Gogo1951** [comment]
Try trading in combat. Still happens. Running and opening a trade on the fly, while in combat, and you lose the Announce options. It still announces but you can't see the interface.
