### ISSUE TITLE
Request for Auto-Rolls on BoEs

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#45]
I think this ticket got closed, but wanted to make the request again.

https://github.com/papa-smurf/Gargul/issues/22

I did a PUG raid today, and I saw someone trade an item. They had GogoLoot... really rare that I see it in the wild, but I told the guy, "Hey you should switch to Gargul, I don't maintain that any more..." He was like, "Can't, it doesn't do auto-greeds. If it did, I'd switch."

So yeah, I think that's the last real feature you're missing. Just wanted to bubble this request up again. Feel free to take whatever code you can re-use from GogoLoot.

Cheers!

**Comment by papa-smurf** [comment]
As mentioned I added it to the todo list, see

![image](https://user-images.githubusercontent.com/4224975/166885374-f536d94a-deb1-469f-8cc6-d0ca925df859.png)

I don't use Github for open issues / tickets / features, I keep a list on Discord, that's because the target audience hardly uses GitHub.
