### ISSUE TITLE
Add support for WowUp

### ISSUE THREAD

**Issue by jimsimon** [papa-smurf/Gargul#47]
CurseForge/Overwolf has blocked WowUp from accessing files hosted on its server. Please consider also publishing to WoWInterface or WowUpHub: https://wowup.io/guide/wowup/hub

**Comment by papa-smurf** [comment]
Wowup is already supported ever since I posted it on wago :)

**Comment by papa-smurf** [comment]
FYI:

![image](https://user-images.githubusercontent.com/4224975/169014517-dd2584ff-7a9c-4d86-b53c-020379d9b85e.png)
