### ISSUE TITLE
Repository is incompatible with WoWUp

### ISSUE THREAD

**Issue by KevinTyrrell** [papa-smurf/Gargul#48]
Installing Gargul for TBC using WoWUp by inputting the URL of this repository yields the following error:

![image](https://user-images.githubusercontent.com/12791400/170089190-fd4c0e25-e258-48bb-b91c-58a429dcfca0.png)

The URL used for installing for the above image was: https://github.com/papa-smurf/Gargul

Consult the guide posted by WoWUp which may correct the issue: https://wowup.io/guide/wowup/curseforge-migration

Given the popularity of WoWUp and the lack of Curseforge as an option, it is highly recommended you make this repository compatible with WoWUp in order to allow ease-of-use when installing.

**Comment by papa-smurf** [comment]
@KevinTyrrell it's not necessary nor meant to be available straight through the repository. WoWup has no problems finding Gargul through Wago, so there's no need for the repository to be "wowup-proof" if you will: the ease-of-use you refer to is already there :)

**Comment by KevinTyrrell** [comment]
> @KevinTyrrell it's not necessary nor meant to be available straight through the repository. WoWup has no problems finding Gargul through Wago, so there's no need for the repository to be "wowup-proof" if you will: the ease-of-use you refer to is already there :)

While I follow your logic, that does not seem to be true
![image](https://user-images.githubusercontent.com/12791400/170103433-efe6c197-d7b6-40f9-a659-d812f167f368.png)

**Comment by papa-smurf** [comment]
![image](https://user-images.githubusercontent.com/4224975/170103955-8ba172cf-a1b6-4716-b183-b5f56ee36cb6.png)

**Comment by KevinTyrrell** [comment]
> Do you have Wago enabled here? ![image](https://user-images.githubusercontent.com/4224975/170104044-0e690450-5f71-42c5-b901-8b6071cb3a04.png)

You got me -- feel free to close this issue.

**Comment by papa-smurf** [comment]
Might be disabled by default, not sure, I'll add it to the FAQ thanks for reaching out!
