### ISSUE TITLE
Packrat Turns Itself Off After Wipes

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#50]
Bug in the latest version.

![image](https://user-images.githubusercontent.com/55365231/176503818-8117ed9b-89d9-453f-8d8c-3fb27dc1f91d.png)

**Comment by papa-smurf** [comment]
Nothing changed in the latest versions regarding the active state of PackMule (not packrat!). Zoning in and out of an area most likely counts as a reload
