### ISSUE TITLE
Typo on Trade Announce

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#52]
No trouble shooting, just a typo I saw in raid.

 [R] [Kikokuu]: {diamond} Gargul : I gave [Conjured Glacier Water]x19 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 to Manufacturd 

 [R] [Manufacturd]: {diamond} Gargul : I received [Conjured Glacier Water]x19 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 to Kikokuu

Should say:

"I received X **from** SoandSo."

 [R] [Manufacturd]: {diamond} Gargul : I received [Conjured Glacier Water]x19 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 and [Conjured Glacier Water]x20 **from** Kikokuu

**Comment by papa-smurf** [comment]
Thanks, will be included in next release!
