### ISSUE TITLE
MS & OS Buttons Don't Close Roll Tool

### ISSUE THREAD

**Issue by Gogo1951** [papa-smurf/Gargul#54]
![image](https://user-images.githubusercontent.com/55365231/188780435-a2fed164-2cfc-44a3-88e8-87e1fe5c4d75.png)

Pass closes, but MS and OS keep it open and can be pressed multiple times.

Latest.

**Comment by papa-smurf** [comment]
Hi! Not a bug. There are several scenario's in which rolling more than once is required:

- Soft-reserving an item more than once
- Rolling the same as someone else

You can enable "Close after roll" or use RMB/Pass to close the window. See the settings for more info:

![image](https://user-images.githubusercontent.com/4224975/188827233-e1020f63-d371-406f-a31e-a31dd99e7a8a.png)

**Comment by Gogo1951** [comment]
Close after roll should be the default behavior. Literally everyone in raid was like, "Why doesn't this close now?" 

Anyway just bad UX in the current state, you really think teams with multiple rolls outnumber teams that only do single rolls?

**Comment by Gogo1951** [comment]
We do loot during combat, right? So like we kill a boss and we're zug'n to the next. And I think that's the way most people do loot these days. So having anything that persists in my field of vision when I'm taking is just cancer. It was way less bad when it went away. That's where I'm coming from. I'll turn it off, but it should have been off by default.

Can you at least add an X to close it?
