### ISSUE TITLE
Rolls are not saved for each item

### ISSUE THREAD

**Issue by Jakobud** [papa-smurf/Gargul#56]
First time using this last night. I think this is a bug and not intended. Here is the scenario:

1. Multiple items drop from a boss
2. Master Looter puts items into their own bag so the raid can continue
3. Later, Master Looter uses Gargul to initiate a roll for the 1st item. Several people roll.
4. Master Looter doesn't give the item to the winner yet (maybe the winner went AFK or the ML is still catching up with where the raid is)
5. Later Master Looter uses Gargul to initiate a roll for the 2nd item. Several people roll.
6. Now, the ML finally is ready to give the items out, he clicks on each item in the Gargul window to view the rolls, but the rolls that show up for each item are the same rolls from the 2nd item. So whatever the rolls were for the 1st item, they are lost. The ML has to manually scroll back through chat to find who won.

Summary: If the ML has looted multiple items and is waiting to hand them out, when he clicks the items, Gargul shows the same rolls for each item (which are the rolls for the most recently rolled item).

**Comment by papa-smurf** [comment]
Your master looter should award the item between step 4 and 5, the way you describe it is not the way you should use Gargul. More info can be found in the wiki https://github.com/papa-smurf/Gargul/wiki/Awarding-Items#items-that-require-rolling

**Comment by Jakobud** [comment]
Hmmm.... interesting...

So what happens if the ML is not able to award the item at that time? What if for example the ML is running to catch up with the raid and is still rolling off items in the process? Seems like the addon could easily keep track of the winner/rolls for each item. The entire raid can't stop every time loot drops so that the process can be followed.

Or how about the common scenario where all loot is looted by the ML until the raid is over then at the end they roll off items 1 by 1? What if the person who wins the first items suddenly goes AFK or Disconnects for a while? The raid is going to want to continue rolling off other non-relevant items and handing them out. The ML is going to want to go back and click on items that haven't been awarded to see who won them. But if it shows the wrong rolls for the item and the ML has to either scroll back through chat or just write stuff down on paper and then what's the point of the addon?

I think in an ideal world yes everyone rolls for an item and it's immediately handed out. But in reality that isn't how things happen most of the time. Honestly seems weird that Gargul would display incorrect rolls for an item when you click on them. Seems like it should not show rolls at all at that point.

**Comment by Jakobud** [comment]
Oh interesting ok so if you use the award button it sets that up? Nice okay thanks!

I would though suggest you change the rolls that show up for old items maybe dont show them or something. It's confusing

**Comment by papa-smurf** [comment]
I can't do that sadly since they're not tracked and it would add a lot of confusion to the thousands already using Gargul

For now try it the "intended" way and see how it feels :)
