### ISSUE TITLE
[Idea] Player option to extend time on rolls

### ISSUE THREAD

**Issue by Nessworthy** [papa-smurf/Gargul#60]
In cases where a player wants to further compare a rolled item but the raid has a generally shorter roll time for convenience, it would be awesome if a player could push a button on the roll window to further increase the roll-able time on the item. For non addon users, this could be supported by a chat trigger e.g. "extend".

Variables / further dev:

* RL controls:
  * Whether option should be enabled.
  * How long a single extend can be.
  * How many times a player can extend a single item.
  * How many times a player can extend in a single raid.
  * The max duration an item's roll window is (including extensions).
* Extend button should not be enabled and should not trigger in chat in cases where the player cannot roll for the item.
* If rolled MS, extension button could be disabled, and any previous extension they have had is ignored.
* Extensions are announced. Everyone's timer bar is updated appropriately.

This is an awesome addon by the way! Thank you for putting it together.

**Comment by papa-smurf** [comment]
Love the idea. Niche use-case imo, but very cool. Will add it to the list on discord (I don't use GitHub as a single source of truth ^^)
