### ISSUE TITLE
Gargul tmb data

### ISSUE THREAD

**Issue by KimiWaDare** [papa-smurf/Gargul#64]
Hi is there any way to extract the tmb wishlist csv data from gargul ? 

Thanks for the answer

**Comment by papa-smurf** [comment]
The only thing that's available is `/gl export` which is populated with items **awarded** during a raid.

**Comment by KimiWaDare** [comment]
yeah but it only show me awarded item. Is there any file where the tmb data are stored ?

To explain everything. The former gm deleted our discord and we can't access tmb anymore and we lost all data. But the data should be in gargul since last raid i did import them with /gl tmb.

Iam looking for those data to try to restore our former wishlist.

**Comment by papa-smurf** [comment]
You could look at your SavedVariables file. It's in `World of Warcraft\_classic_\WTF\Account\YourAccount\SavedVariables\Gargul.lua`. There is no import feature in TMB so you're gonna have to manually add everything again

**Comment by KimiWaDare** [comment]
thanks a lot for the help have a great night :)
