### ISSUE TITLE
Font garbled issue in loot trade timer with korean client

### ISSUE THREAD

**Issue by coderhyme** [papa-smurf/Gargul#65]
Text of the loot trade timer bar is garbled with korean.

![1](https://user-images.githubusercontent.com/7882097/199957878-b4e2ffe8-b7ae-47af-81e0-63ead96c7a7b.jpg)

I figured out below line causes the issue.
https://github.com/papa-smurf/Gargul/blob/b76a48f5bc5f1758f5cb0aa0940ede84e677dedf/Interface/TradeWindow/TimeLeft.lua#L550

After removing this line, the issue has been resolved.

![2](https://user-images.githubusercontent.com/7882097/199958689-6d471549-9177-467d-967e-6204b9e0ce2b.jpg)

**Comment by papa-smurf** [comment]
What does replacing that line with `TimerBar.candyBarLabel:SetFont(TimerBar.candyBarLabel:GetFont(), 12, "OUTLINE");` look like? :)

**Comment by coderhyme** [comment]
> What does replacing that line with `TimerBar.candyBarLabel:SetFont(TimerBar.candyBarLabel:GetFont(), 12, "OUTLINE");` look like? :)

It works!

![3](https://user-images.githubusercontent.com/7882097/199964999-f86f284e-4557-46b5-baf6-4be81932b088.jpg)

**Comment by papa-smurf** [comment]
Thanks, will fix in the next release!
