### ISSUE TITLE
[Request] Keep Loot list window showing while in a raid group.

### ISSUE THREAD

**Issue by scarecr0w12** [papa-smurf/Gargul#67]
Is it possible (If not already suppose to), to keep the loot list window showing when in a raid group, regardless of actually being in an instance or not. Having to search through my bags for the right items after a raid is complete, and we if do loot outside of the instance itself, is annoying.

if there is a way to have this done, can you advise where, as i can not find a setting/option for this, and it seems consistent across different players in my guild.

**Comment by papa-smurf** [comment]
Hi, whether you're in an instance or not doesn't matter. What does matter is whether you're the master looter or not depending on the following setting:
![image](https://user-images.githubusercontent.com/4224975/200116493-ef89d280-7617-47d6-80d3-dffb43ff5a2a.png)

The loot trade timer window can take a while to reactivate after switching zones (this will be fixed), until then you can change anything in your bag (i.e. move an item) to force it to show again
