### ISSUE TITLE
The roll window doeasnt appear in raid

### ISSUE THREAD

**Issue by Halfino** [papa-smurf/Gargul#68]
Hello, I had Issue tomorrow in raid, the roll widget didnt appear at all.
When I tested it before raid on junk item, it worked correctly, but as soon as I used it in raid, no widget appeared (guildie ML, me and my wife rollers with gargul installed)
I am using this settings.

Thanks for answer

![image](https://user-images.githubusercontent.com/1391038/200539196-57bb086e-8813-43ef-8601-a075de2cfcee.png)

![image](https://user-images.githubusercontent.com/1391038/200539516-6d396021-1b8a-4bc2-871f-9c00e423e136.png)

**Comment by papa-smurf** [comment]
1) What version are you using?
2) `guildie ML, me and my wife rollers with gargul installed` - Does this mean that the others did get it and only you didn't?
3) What error did you get? `/console scriptErrors 1` to enable error reporting for your current session

This should be easy to test again by getting in a raid group and rolling out items. If you can consistently replicate it then I'd like to ask you to record it if step 3 doesn't produce any errors

**Comment by Halfino** [comment]
1) I used tomorrow the 11.5.2022 release version. Checking updates once a day only.
2) Only the master looter had seen the roll widget, others dont. I am not sure who else had Gargul installed so mentioned only 3 persons who I know they have the addon. The behavior was same in/out of combat
3) Will do so on next monday pug and make a report

Thanks for now

**Comment by papa-smurf** [comment]
They most likely have outdated version. The master looter can check this with `/gl version`

**Comment by Halfino** [comment]
hmmm...Might be an issue if the widget doesnt work cross versions. me and wife had same one as I installed her Gargul right after update of mine and it worked, but ML had maby older one...
Leave this for a week please, will confirm / report after diging on next iteration of our pug. I will also make some research in smaller groups in general.

**Comment by Halfino** [comment]
Hello, seems the issue was the master looter didnt have updated version of addon and all worked perfectly this monday.
