### ISSUE TITLE
Loot stays in the Loot Trade Timers windows when awarding to self

### ISSUE THREAD

**Issue by Jakobud** [papa-smurf/Gargul#72]
I picked up an item last night that I awarded to myself. It still stayed in the Loot Trade Timers window, giving the impression that I still needed to do something with it. How do we prevent this behavior?

**Comment by papa-smurf** [comment]
Hi, this is by design and will take a bit before we get around to changing it, but it's on the list :)

![image](https://user-images.githubusercontent.com/4224975/203647834-84096405-ff3c-4525-baea-cf1f0e01af70.png)
