### ISSUE TITLE
Gargul added an animated highlight border to my raid frames and I have no idea how to remove it.

### ISSUE THREAD

**Issue by tamayopa** [papa-smurf/Gargul#83]
I installed Gargul the other day and suddenly, on only one of my characters, the very same highlight that Gargul adds to items has been applied to my VuhDo frames.  I didn't install/enable/disable any other addons, and I didn't change any settings.  I've been through all of the VuhDo menus several times over and it's not something I can disable there (I don't think that's even possible with VuhDo anyway).

I've tried disabling Gargul and it persists.  I've tried disabling literally every addon but VuhDo and it persists (I'm really pretty certain this isn't a feature native to VuhDo).  I've even uninstalled Gargul and **reinstalled** VuhDo, but it's still there.  Is this a known issue to Gargul?  How can I troubleshoot this?  Any help would be greatly appreciated.

I'm going to go absolutely insane if I have to raid looking at these eye-piercing animated highlights.

![image](https://user-images.githubusercontent.com/122917040/220586903-066d91f6-357d-4e04-a86e-21583913fc1b.png)

**Comment by papa-smurf** [comment]
Not related to Gargul in any way shape or form, check with Vuhdo or other add-ons / weakauras you're using :)

**Comment by papa-smurf** [comment]
You sure it doesn't refer to (missing) buffs in any way?

![image](https://user-images.githubusercontent.com/4224975/220595217-8c7f6f6e-f4a8-4016-b980-ac3cd6749616.png)

I find it a bit unreasonable to presume that an add-on is responsible for placing an animated border even if it still occurs after disabling or even uninstalling said add-on.

**Comment by tamayopa** [comment]
> You sure it doesn't refer to (missing) buffs in any way?

I wish it did.  I've already looked at those settings and toggled basically every possible combination of them on and off just to be sure.  I'm really quite convinced that VuhDo is incapable of producing this specific animation on its bars (the animation setting in your screenshot refers to an effect on a debuff icon, not the whole bar).  If it is, I haven't been able to find any mention of it in the settings or by Googling it.

> I find it a bit unreasonable to presume that an add-on is responsible for placing an animated border even if it still occurs after disabling or even uninstalling said add-on.

I mean, I wouldn't disagree with that if I just randomly decided that your addon was responsible for my problem for no reason at all.  But literally the only change I had made to my UI in weeks was installing Gargul, and that's the instant I started seeing this on my frames.  I've seen WeakAuras produce this exact same effect under the settings\Display\Glow\Pixel Glow, and seeing Gargul produce it as well, I figured this effect might come natively from the game client itself, and therefore be something that an addon can "toggle on" so it persists even when that addon is removed.  That might've been a stupid idea; I don't know the first thing about LUA, WoW's native effects, and how addons interact with each other.

Anyways, if Gargul is completely unrelated, I apologize for wasting your time! 😔 🙏

**Comment by papa-smurf** [comment]
Hm like that. It doesn't make sense for me but I see how you might've come to the conclusion ^^

An add-on, Gargul or any other, is unable to put a highlight on anything after it's disabled or uninstalled. The only influence they could have after an uninstall is that they changed settings in the native UI or other add-ons.

If the highlight is present with **only** VuhDo enabled, and is gone after disabling **VuhDo**, then it's VuhDo, 100%, no question about it. Then the thing you'll have to figure out is where it comes from. A VuhDo update? Something or someone changing your VuhDo settings? An error of sorts (enable error reporting with `/console scriptErrors 1`).

Hope you can find it!

**Comment by tamayopa** [comment]
Thanks a bunch for the reply, explanation, and advice.  😄 Much appreciated.
