### ISSUE TITLE
MS button /rolls 100-100

### ISSUE THREAD

**Issue by scottlonghofer** [papa-smurf/Gargul#84]
When hitting the MS roll button, gargul will roll 100-100.

**Comment by papa-smurf** [comment]
Most likely not a bug. Check if you or your master looter set the roll
range of MS to100-100 in the roll tracking settings

**Comment by scottlonghofer** [comment]
Funny, I just thought of that and was about to comment saying the issue didn't happen in another raid.  Sorry about that.
