### ISSUE TITLE
[Request] Highlight if 2 or more players have same highest roll number

### ISSUE THREAD

**Issue by Lawdie** [papa-smurf/Gargul#85]
When trying to sort loot out you can often get caught out where 2 people roll the same number, it would be great if the addon could highlight when this situation occurs so you can prompt re rolls. 

Context: Accidentally awarded loot and never spotted someone else rolled the same number until they had equipped it.

**Comment by papa-smurf** [comment]
Hi! I have never ran into this issue nor have I had any similar reports. That doesn't mean it's not a valid concern but that does mean that I have no idea what to do or show to make sure that you know something needs your attention :)

Doing anything to the roll records (the rows, the ones that get a yellow highlight when clicking them) is not possible sadly, but maybe you can think of some other soltuions that would help you?

**Comment by Lawdie** [comment]
My first thought would be when you "award" the item there could be a confirmation prompt if there are multiple people with the same roll

"Are you sure you want to give PLAYER1 [LOOTINGS]. There are multiple matching winning rolls"

**Comment by papa-smurf** [comment]
That I can do, consider it done!

**Comment by papa-smurf** [comment]
FYI, this is what it will look like after the next update:
![image](https://user-images.githubusercontent.com/4224975/226999051-198a04c4-1223-4325-bfcc-ac47dc902063.png)
