### ISSUE TITLE
Roll Window doesn't hide

### ISSUE THREAD

**Issue by catpokemon** [papa-smurf/Gargul#87]
The options under Advanced > Rolling don't seem to have any effect on what is displayed. 

- The first checkbox Roll window doesn't impact whether the window is shown or not. It is always shown.
- The Close after roll option doesn't impact whether the window auto closes when rolling. Currently, it always auto closes.
- I did not get to test it on "Don't show on unusable items"

Thank you for all of your work!

**Comment by papa-smurf** [comment]
1) The roll window always shows if you're the loot master (not sure if this still makes sense after implementing 3)
2) Can't reproduce this one, need more info
3) Very easily testable by getting an item from wowhead or atlasloot that you can't use? Don't really understand this one if I'm being honest.

Let me know!
