### ISSUE TITLE
Auto Bid Feature Not Working

### ISSUE THREAD

**Issue by NotWarlock** [papa-smurf/Gargul#93]
Autobid feature not working even with completely fresh install of Gargul. No buttons on the bid window function; Minimum is clickable but does nothing, Auto Bid is clickable and pops up to enter your max bid but does not work, Pass closes the window as expected.

In the loot preview window when you set max bids that function also does not work.

The only loot addons enabled are RCLC and Gargul

**Comment by papa-smurf** [comment]
Hi @NotWarlock, most likely you enabled this setting:

![image](https://github.com/papa-smurf/Gargul/assets/4224975/e67339e1-7c8c-49da-babb-094bd06bdddf)

If that's not the case, then provide your `/gl bug` output.

**Comment by NotWarlock** [comment]
Hi - this setting is not turned on:

![image](https://github.com/papa-smurf/Gargul/assets/24915483/f98ad7b4-6891-458e-8f8f-933261089a68)

Here is /gl bug output:

`eJylWm1zIjmS/itsXWzsXYThKN5sei4uGjC22QbDUnR7bmYuHHKVAI0LiVGpcNMd/d8vU1JVqcpgd8R92Jmx8ikplS9PZor97g2iSPBrooj34bv3t2G6uZXk6YlK78Pv3sFvNvxG27tQMqX/e+ENRgtcbje6jX6xGNI2ri5pTElC69JvN0G6JnFixbefJ/V2o/kY3Pxaf2DRhqoEP4CdG01nG8UEHxIZkAOVsJkgEY0MrtnoFrgomvPgmXG9R6fRu3JEB8JDGk24onJNQjrf4572sKtGr0DGSmxFzEJznU6j2Wy9Fj4Owi2jB7qj3Gj8BnJDeUTexoy2RJIQVHtnr1vJovcgKYujtyEBJTLcvoNJdzsijydBfCOPgyRhG55f/+A3/G6j5fhWxSSZCqFG8O/EWPPQLodMBfI4EnFMw9wv78IlWSvGNz+DNVH8E7iUbyicP+DRklhbv/fNDfl5nZ2wew+6OCxOwlTKqXaL75o71ToQJXR26uT0nfBPlbimiZLiaCK+9KkSU7HZUOm6qoWn1l+Eip/DujT5m283ZJsHtjG3aPWbqF62mxWBLyV9S+4a4gxkEacbdgaSbgISPhdEVJCAvcQgleQa/pefoqO4igr2NI6RXg45kKdxnKNELOSChc9UgjJV6fVwVh98o1Ko7QlJZoBm2O+2oyJ7UAasd040TyEOuAm8q3U3bPYuS/IFkepYH45OnGhEXwhncUzOyh+Emn7C3dd9ug7bT+XdTcxJv9ssretcMKee1MrIi6PfAD2IlTnfp/5Vs31VggSKqDQBpl+xnSXDU0b6svgynqGQ+t02vWyXhA9CxtH4YJmpZIRAf9Qp4MAKgbKOajVbUHS6jeYJ+Su6z8HtU+Cc8TOYk4oOLA3L0dn0T6DKpeHNc0eCK8J4qYqc3BKJ8z1MKiXlIaPJu/eYcDS2cIvFqR1nhMXJu4b+Vwo09Y5uS7pPFfkJ2+n0ft9uKxKXy7izF/2TZFwBRxpMs9NsSRejsqv9m/3vBp7XvGqBxfyr7iXUxm4VDt7a7YmkrWqQWnGmHtnQM4gxD0WK/UyhwCkYpt1oSzVbnpIHSlKy013dKfGK8eNqCxB1BgBZv0mJjCri8W//TLlmaGzSCrOPf9MuPiGID4YW/Xaj3S8vP07ZkyTSRuMpgNvPnRfbAxrNq4p8SSOVfrPq9opCY6RgAygBKyHiJ/HVYFoFI91ef1rYjstvdIpvb4ncpDEKeo2Wc9FborZUzojSvoe9Opf10JZe5+McVDQvGFX1Zq/eunSAMYkinXqtRqtTX2alOpdjP/i4FAkECuQgh3gyLUIDeDXX6Y4+s5jpQzAFWnUdwJfNfl2GfrHZneDfGDYpVvGGI5soulvaotxuXBYBnwkKF7lxglK0rGL7hRRrCmYQfBJmvQFOAn79AQr5Nt9wCsEo2Ve4zd4mLbQAnd4rua3Zr+Xs6RZa4CCE5K9DMGSxKC9dSKDSp0zX7I6z5QrBncteUR9nwXB1+mozkvyV6tpS6VGM4HFEmG4dzoh17NF8C6d7mbHnIJTQLUP3OyRKxXRFv2qfwPTl4o5JbHx1ACaCQ+rGu4XT7sFUM8bZjuytuQHWLFS5Fwcy4YnC4WkFdeg5C55OGaNJBgmNgx0Mou3EBkJ0XR6m67Uh5EbXSZX5jrPRKDdFwa1GgJVtzTYV8y5IHB8X4iUbSGH0bBWJlIHoZhOb+g6R5GT2Iobc0l+a/6ofur12JdAgIP+EgWTwjcVSPBNzr6uCOzST/apbpiYMkX5ZwPSxVyAo4mo50i0+8HbI4ken4YZru55b/rqAxI0M3x06DVN6M92XUDeCkHBuLqB9ivGTy3WBfIpt4LQvTSPvAESqaJZgPbezDqDdoNGMRsyOrOCNut8v+NQBPN6IP/9kFa+48tkx26iEYLt9TGcm4oBJHbsFMdwZ2j+UXGLm1/79v/4eiohyqFB//+//cPQUaRwIaYmoXXuYY1uZ71Pu6+cHKmNyNHbuNwrqDl5otKG62UThHxAk4Mg/vOKcFQnFiu3Npx2HxU3TYJ4hDq2W32pevpI93sbH/fZGgvIGBjt0X01TORq0DlfkqUojKwEEudMb4POKX2yQK4mZuaSJSGVo3ArhdIXh5CAiGgDHx0AuNu4hrKBU+oX1q6DHwX5/R+O9A8+xD5Q844ylT+s2Lp3YzUUDCV3zgb6BKFEG7H8KMwP3xwtIy7eOcsr/GcSKQtQRG/UVjHiBmEzGX/cQUOayLYeO2UzIveFpLCSV9XuqXosUuA84kW8K9neop5BWiC0DpJypBPLb+rxZMPYPKE2CRHnH9x2ugnz5we/1W36nddVrXsBSC4uau9TLl/zuVa/T6pil1mtU2yz1/U7zqn3hAUOpqX5vm3MtafvdVr/XRwkYU32BaQMsD1MKXCcJtuIFYPY4UBbKFNursZQChxIPLOQFVOGrjVZ+8AKNI/xhWorvHlAaUiPV6zPoBaBbSSZc9zBwBGC0GS7OAZcPBSJVwjxSDdbg1OykAceGw/uAjjIgHfU/g7lmCUxEcFEdIxXhhEMsP6GGVuAqNuZIxlFJNudLGlKdHpnGpWVdldPdv1ISMwXU1QFrDgW2cdFSxMb3ePoOGC7ESjgIQ7pX2CveSKQLILEyQDOz6SWNHhFdkzSGaoTtuN/MFxaC6XHIbxZrgaJ7A6L6Mg9blgAxwKV3hOc3o9lF7ZXW7Guurl0CgueKrRna0BsuQcm9ZELqO/oXnqQJlQeKE0eyFfiS6V814erXUuz3NKoGirNc9r6Vo2AlTOgYFXclu87XA4u0W3deI/TjWCYGVQxPOFEbpgmY+UbIHR7jfZxc//LxerAa1z6uJrPxLx8fJvf3Y7xp5ETQxLXDoyOJAMh4GKeliIswJJPsElY+h2YKakZJBFZ7QcWKB9olhRtFWcz+MAML6o3fTemBxsUACeQzw9lapyv+lWXrAjTWSYGLRIfakEXJFNuvFWhow7VwQBQN52N0T7IS0A5hE2ujP4rOLN+Cv1cmnR5AY/GSy7JsNy8mMIlLVZWhNqNYJE6aWQl2Wwp24yZCysIbxkk8gvSoCu7pC2x5evXURgswuSYRo2MhVizgbA/39LuYkFo65tGU0hdsSVqWqjD5vzBiP6cFxTyxCJynbXUHyfOZp4lp7ayljRzaQVyDDArRCMU2c663zuEmWE0MOyG7Gs8ubKBefLydT6/hr/nD3Xhw7ZW/uaNEx5KOngvonY9UXqDnLqCMbkEIQ8lz/g1YpXrUYjr4Hzxk9Hn1GpbvbjcepcrLOWjCQ6mf4MrUZENPe6tr1uHjIVUvlHJtt6h4avN1FqIBtaTgJUNdw8LYOaeV9PeR1GzIYN9oOJHxA5BFhDG4kgzf0geF3802MXaaWXRYb7Wblm3Yt5LHSgFu6QhzpigGFx4XwB7HyRrOhPF5WiQLT3dPsMn6BopIQGGQBp1EngMmDDPMKTmIYTqAqIIWG5ndvmN8qKXbutgiX1d9Cjb5Cy02Se5IrIoE/Mu1/b1A6wxscnjBp8nCM2wF6+V0x8U7luCT4pzbtwFXpt1T+QQf8mwgDHiUR0pOWwamtMfQ7C+mfmHg5uxn6VHXDCSh7BH6uzeU0AKFJDF0v8XJK9b3tkSsUyzn6KzSnSXxMuAOY46fFKEGU7ouYoF8xRvm2hkZzB7VqmVCxHrZbt3COkrLrciW5crnZztrKxHQeF2SuNfJBVave3sgTHCJDqQ39E1ywtLuFuqZHsuVykjmPD4+bCk3Iwn6Rv/kZ31VWYXGIAZWTT4n9NqQw71Q9FVXkEf7HP54JS32RE3eENr2DrnwH7tamoAKNbWlNZMwNYI/n9eUqAHhKMmeYOSuxfBho3YNR+OP2DWmamxdO4q0BtB/qNoLmBW/2LEkqUEW1mADfOdJ/uYVKmA/NeavShMulysjlJX53rUcldeMxGKTISyB4pfQShhTef+JB9bWQtZmQQ3+af7u9/XSPEA6dunCshuQ/j3SQQzZd4etL0xt5ZB+h3P2kq6pxKcD16VOH9j6gU8+4fMsxbj57i3h37ZJybvBc/0SmkKPWnJ3K0W6P7EeiFiUhodrUyaA5PQnptmzJcEkUVlUqiMoKy6SWwn++1ZfxoYvvlDOOf3/NfNZHxCL8Pn18vl2/Qe+A0EVw8cDmz1D/cSnf+b43ZuBr/0LrLQtM31m8+nv3lyL+v2Ltp54rQA8kUBZGB4DsYaus2hJ9eJqNlxAp/9q8YEl25gluZEU6jDAhkzvarW0CprmBvssXMwvWSYTG89uhcBRdAsnhqn6RI/W3lktup4Eg+F0jJ0OMb2SN5iuHoO7yc3qcTSdjD55edeAVDSazia6kjnDW9HAw9ej1XJa/Vyk8PUoZuGzbXGz+wogOBhxTVja3aS5QVk3uzgvWkytZnaCbvwp/vRYXDnzQzEwTfhaTLg7ELkSvF1ubTfWbRVOyqunh0AY+kz3dk92RRBg7cAj5usFFfuY3uPE5iQjqAvBgKrOgztiBotFPhmWVcV1DJkzKmewLLLOwd7Op/cUNgg8Y2rPmKwzhSfJAgdZnhvZ1nOU52iuxzSr6+41uLT1WXCl9LqQMVfmJ7PuK5j1Z45odzGAwATgUkVNOno2qCwILWhIsijOjugzlj+8X9sFIAtrI/JqBKHUNcdpBP6uULI5LrqGqX72wz5junZIisYgWx6bXLXSLKbztVtIbX5i3b7N5KG+ATIvYXGhCmJYiUoovVKFvfMwgS2eQNbwYCq7f5wNgtV4OZ3P4Z/40JYVe5uL+GybbRzqt7kplv2MrOhTusEKPa6+1wiuAhhGgEp9jO8N5M9mq7CgL83DTLmu5ojZUa9js+YkkBVm6XruY0tTb2yfZfI5efWFjYvs6a1oP4SeZ/Jv91KsWUxl1QQYYPYXsWGqVDHJo+DzPiKKDuCzouAnuO0omwm84OZXyJsXGodiR/MO0YZmGDOduvr/QgB+wN/4me5B8WW21+r3Oj0IohRHWTsC1zvtq0692eyPRwO/D1tz/WuCB3T0RPSkLSmJsUWYwZ+SPXs//u+xwB5j`

**Comment by papa-smurf** [comment]
So if you create a session in `/gdkp` and auction something off, nothing happens when you bid? If so: record it please. This is not a known issue so I have no leads as of now sadly :)

**Comment by NotWarlock** [comment]
Correct, nothing happens when I click the bid/etc buttons.

Recording: https://imgur.com/JIZ9OPj

GL Bug:
`eJylWn1zIrnR/yocqVSSKsPD8OKXu1RqAWObLBjCsOt7ckm55BkBOguJ02jwslv73Z9uSTOjGYO9Vc8ft7uof5Jare5fd2vuW70fx1JcE03qP3+r/zRI17eKPD1RVf/5t/o+aDWDZqd+plVK/3tW7w/nONxp9ppXxWBEOzi6oJyShDZU0GmVpLefxo1Os/UY3vzaeGDxmuoE8bBws+XhNJNiQFRI9lTBWpLENLa4VrNX4OJ4JsJnJswa3eb5pSfaExHReCw0VSsS0dkO13SbXTbPCyTXciM5i+xpus1Wq/1a+NiPNozu6ZYKq/EbyDUVMXkbM9wQRSJQ7Z21bhWL34OkjMdvQ0JKVLR5B5Nut0QdjoLEWh36ScLWIj/+PmgGvSZgVoQnBqQ5SSZS6iH8nVhr7jtlj6lAHoeScxrl9/IuXJGVZmL9I1jrxD+AS8Wawv59ES+Is/V7c27Ij+vsud170Pl+fhSmU0HNtQS+uVOjA9HSBKeJzcBz/1TLa5poJQ/W40tTtZzI9Zoq/6rauGvjRWr+HDWUDd98uQFbP7C1PUX7qoXqZas5Edylom/JfUOcgMx5umYnIOk6JNFzwUMFCbhD9FNFruG/fBfjxVVUuKOcI73sc6BIOc9Rkks1Z9EzVaBMVXo9mDb6X6mSenNEkhmgFV31OnERPSgD1jslmqXgB8I63uWqF7XOL0ryOVH60BgMj+xoRZ+JYJyTk/IHqScfcfXVFV1Fnafy6tbnVNBrlcZNLNhdj2pl5cXWb4Ae5NLuH9DgstW5LEFCTXSaANMv2daR4TEjfZ5/Hk1RSINeh150SsIHqXg82jtmKhkhNJO6BRxYIdTuotqtNiSdXrN1RP6K7nNw5xg4Z/wM5oWiB0ujsne2giOocmp4c9+hFJowUcoiR5dE4nwPkypFRcRo8u45xgKNLf1kcWzFKWE8edfQ/0qBpt7RbUF3qSY/YDsT3u/bbUl4OY17a9HfScYVsKXFtLqttvIxOjvan9y/m7hf67INFgsuexeQG3tVONzWdkcUbVed1Ikz9ciankCMRCRTrGcKBY7BMOyGG2rY8pg81IqSrSnqjomXTByWG4DoEwCI+nVKVFwRj/79z1QYhsYizePu0b/NHR+T8L0lxqDT7BRlohl+nLAnRZTzx2MAv6I7LXYbNFuXFfmCxjr96hQ+ryiFVoAksJSSP8kvFtMuOOn2+uPc1VxBs1vMvSVqnXIUnDfbXhK/JXpD1ZRoc/uwVveiEbnk603OQUX5gn7VaJ032hcekJM4NsHXbra7jUWWrHM5VoSPC5mAq0AUCvAoWyQ0gVlzne7oM+PMbIJB0G4YF75oXTVUFBSL3UnxlWGZ4hRvFnEw1nS7cFm507zoFZMySXFFxlN8MZpWs91cyRUFO0gxjrLyAJuBoPEAuXxTLDkBh1TsC5xn5wIXyoBuUcZncpe3X8vZ0y2UwWEEBNAAd8jcUV34kFCnTxW/ni6WiO1enBcpchoOlpWzZRKS/JGa9FIpU6zgcUiYqR5OiI3z0XwJr4CZsucwUlAwQwE8IFpzuqRfzKVA/+XjDgm3l7UHMoJNGvZ6C0veg6WmTLAt2TlzA6zl3d693JOxSDQ2UEvIRc+Z+3QLfRFjiAZJTYAhLKITlJcxuXmQrlaWlJu9IgXMtoINh7kpgooAk9uKrSvmnRPOD3P5krWk0Hy2i0jKQHS95jbFgyd5oT3nEFxmpv1XY98772SOlk1W8nfoSfpfGVfymdhjXRbkYbjsV1M1taCPDMoCZra9BEHhVouhqfKBuiPGH72aG47t39zi1zlEbmwJb99t2uyb6b6A1BFGRAh7AHOnnv/YFPnEnd90LmwpX8hlqmkWXuc+CYdQb9B4SmPmela4i0ZwVdCpB3i8kb//zip34sunh2yhEoJtd5xOrb8BkXpWCzmcGOo/lFxg3Nf++vc/RzKmAlLUn//xtwIoUx5K5WioU3uYYVlZnKJc2M/2VHFysFa+ahbMHb7QeE1NtYnC/4CLwDX+p16stCSRXLKdndr1SNxWDfYdYt9uB+3WxSvZ4y0/7DY3CpS3MFih96qdytGgdbQkT1USWUqgx61ZAJ9XgmKBXEkMywVNZKoie63gTJeeMwEgpiEwPAdmcU4PPgWJMghOgh77u90d5TsPnmMfKHnGHsts1mteeHvlor6CqnlP30CU6ALWP4aZwu3zOcTkW1t5yf8EYknB6Yhz+gpGvoBLJqMvO3Aoe1g/lthUqp0laUwilfF7ql+LNNwe8KFYF9R/fkR4nNRSwXQCoe0uvFWQ9XdISpLEeb33DQ6CVPlzcH7VDroXQe/8DIbamM78ofN8KOhdnncDN9R+jerYoat267LTPasDOemJeW2bCSPpBOe9bu8CJWBK/Rl6DbA79ChwmiTcyBeAue1AWchQbKdHSklsSepgn3pINb7ZGOX7L1A2wg9bTnyrA5shK1IzPoUyACqVZCxM/QJbAMaY4ewUcPFQIFIt7RNVfwVXmu3UF1hr1H9GS1uQ8fkfwVyzBPohOKjxkIpwLMCTn1BDJ/AVGwkk4rgkm4kFjagJjkzj0rBJyOn2XynhTANvdcGaA4klXLyQ3N497r4FeoswCfajiO401ok3CrkCGKwMMLRs60irR0xXJOWQiLAWD1r5wFwy0wwFrWIs1HRnQdQc5mHDEqAFOPSWiPxkNDuoO9KKfcnVdUPA7kKzFUMb1gcLUHKnmFTmjMFZXdGEqj3FfiPZSHzHDC5bcPRrJXc7GlcdxRsu376To2ApretYFbclu85WfYd0S3dfI8zTWCYGVSxLeF4bpQmY+UaqLW5T/zC+/uXDdX85qn1YjqejXz48jO/vR3jS2POgsW+HR08SA5CJiKclj4vRJZPsEE4+gzIKEkZJBFZ7QcWK59kFhRPFmc9+t80K6o3zJnRPedE+AvlMsbM24Yq/smidg8YmKHCQGFcbsDiZYOW1BA2duxYXEMeD2QivJ1lKqISwfnXeH8cnhm/hvpc2nB5AY/mSy7Jot+8l0IcrXZWhNkMuEy/MnAQLLQ2rCeshZeENE4QPITyqgnv6AkseHz220BxMbkjE6liINQsF28E5gx4GpJGORDyh9AXrkbajKgz+z4y46bSgmCcWw+UZW91B8HwSaWLLOmdpK4dKEMcggiI0QrHMTJilc7h1VuvDnssuR9Mz56hnH25nk2v4NXu4G/Wv6+U5d5QYXzLecwZl84GqM7y5M0iiGxBCP/KczwGrVLeaT/r/i5sMPy1fw/LV3cLDVNdzDhqLSJkHuDI1Odczt9Wz4zB5QPULpcLYLS4e2gIThWhAIyl4yVLXoDB2zmkl/QMkNecyWDRaTmRiD2QRow8uFcOX9H5x73YZjmVm5h3utjotxzbsa+nGSg7u6AhjpkgGZ3UhgT0O4xXsCZ3zpAgWkW6fYJHVDSSRkEIPDTrJPAasG2aYY3IQQ2sAXgUFNjI7tG2CIk1XrxJM8QcaapzcEa6LuPvDN/m9RKP0XUzUw4/jed2SFIyXoxwH71iC74gz4V4DfJm5lcoUfL1z998Xce4gOVtZmDYXhdZ+sWkL/TUnPceKJlUg92Qvz9/qAwWVT0QSy/Ib7LW4ObfjXxNZOTVnCe4kd5cBd+hq4qgINZjQVeEC5AueMNfOyqDfqCYr6xnuct3SbUyftFyBbFiufL63N7aUIeWrksQ/Ti5wet27DaFrS4z/vKFvkvOUuW6pn+mhnKCsZCb44WFDhe1D8G7Mdz53V5VRqAc4kGnyKaHXlhPupaavioHcyWfw45W0WBM1eUPoqjqkwL9sa2kCKtT0htbsW1+N4CfzmpY14Bmt2BO02TUOE5u1a9gav1zXmK6xVe0g0xpA/6JrL2BWnLFlSVKD4KvBAviyk/xUL1TAMmokXmUkHC4nRMgms51vOaquGeFynSEcb+JMqCCsqer/gxvWVlLVpmEN/rS/r67M0CxEFvZZwpEacP090gGH6LvDihdatbJLv0M1O0VXVOFzgX+lXvnX/o6PPNHzNEW/+VZfwN+uNsmLwFNlEprCNFhqe6tkujsyHkouSz3Dtc0OQHJmiq3xXCawQVQWldIHyoqD5FaCf9+awzj3xSfJmaD/vxo+S/9cRs+vh09X6d/x7QeSFz4YuOgZmDc9823jt/oU7jo4wwTbtk1n9sbwW31mRFdXZx3TqToB3EQCaWFwCOUKis2iEjWDy+lgDgX+q8EHlmw4S3IjadShj3WYWdVp6RS0NQ2WVziYH7JMJs6f/QyBHegGdoxS/ZEenL2zXHQ9DvuDyQgLHGJLpHp/snwM78Y3y8fhZDz8WM+LBaSi4WQ6NpnM69mKuh1mD5eLSXW6TGH2kLPo2VW22XklEBx0ttYt3WrKnqCsmxucFZWlUTPbwdT7FL83FkfO7qHok8ZiJcfC74N8CZ4ut7bv6y4LJ+XR470f9Hq2aLsn28IJMHfgFrPVnModp/fYqHnBCOqCM6Cqs/CO2H5injeEZVVxHF3mhMoZLPOsU7C34+k9hS0C95i4PcarTOFxMsf+VeRGdvkc5TlamO7M6bp9DS4tfRJcSb0+ZCS0/UrWewVz95kjOj10IDABXKmmNhzrzqkcCC1oSbJIzp7oE6Y/PF/HByALGyOKqgeh1DfHcQR+SCjZHAd9w1SnfXdvl74dkqIwyIZHNladNPPpfOwWQlscGXdPMrmrr4HMS1gcqIIYZqISyoxUYe+8R2CJJ5E16tCM3T9O++FytJjMZvAnvq9lyd7FIr7VZgtH5klugmk/Iyv6lK4xQ4+qzzRS6BB6EKDSAP17DfGz3mhM6Av7HlPOqzliejDjWKx5AeSEWbiemuxo6o3ls0g+Ja8+rAmZvbgV5Yc0bUw+d6fkinGqqiZAB3PfwAap1kUDj4JPu5ho2odpRcJPcNlh1hO4ihRC54XySG5pXiQ674w4M9Fr/tcBuAr8ts9MGYpvsudB56p1Dn6UYhPrmt9Gt3PZbbQ6F0H78qYDSwvzEQH6MZ18xcRACd+arcWzYs/17//3S54bIg==`

**Comment by papa-smurf** [comment]
Hey @NotWarlock, all I can think of (assuming your buggrabber/bugsack are empty) is a UI-addon throwing a wrench. You're running quite a few that I'm not familiar with, so it could be worth a shot trying. You're running addon control panel so hopefully that helps trying this out real quick :)

**Comment by papa-smurf** [comment]
Closing this since I have not received any further info, nor anyone else with the same issue. If this does pop up again, please let me know! :)
