### ISSUE TITLE
TMB Wishlist RollOff Announcement Incomplete Player List

### ISSUE THREAD

**Issue by nhempel** [papa-smurf/Gargul#94]
Hey,

our Guild recently started using TMB and we noticed some odd behavior. 

When the Wishlist position is tied with other people (and no priority is set), only one person gets added to `EligiblePlayers`.

Trying to debug this issue I found that line 212 in commit 2a149345be7f2fd0155a1a9cf3b8896d0386418a Classes/RollOff.lua was changed, where `Entry.position` is compared with `EligiblePlayers[1].prio`.

In all my testing `Entry.position` was always a `nil` value (with multiple TMB Guilds, exports and items), changing the condition to `Entry.prio ~= EligiblePlayers[1].prio` had the desired result of the all players being announced that had said item on the same Wishlist position.

Not sure if I have missed something, so a look into this would be appreciated.

**Comment by papa-smurf** [comment]
Thank you for your report, this will be fixed in the next release! :)
