### ISSUE TITLE
Feature Request: Ability to merge import

### ISSUE THREAD

**Issue by einard85** [papa-smurf/Gargul#95]
Atm I can only clear data, but I wish I could import again with additional data.
I was hoping we could have the ability to import and merge into existing.

We have two raid night sometimes.
We want to award people 2 SR the first night and then add another for the next night. Basicly two different SR sheets.
We only import the first sheet on the first night, and both on the second.

**Comment by papa-smurf** [comment]
Hey [einard85](https://github.com/einard85),

This should be implemented on Softres' end, since it's considered the source of truth for our SR data. You can find their discord here:

https://discord.gg/PkX5eVm
