### ISSUE TITLE
Raid warning posts wrong item level

### ISSUE THREAD

**Issue by Tindrith** [papa-smurf/Gargul#97]
Every item postet for a roll start ist always level 441 and never the correct link.

**Comment by papa-smurf** [comment]
@Tindrith do you have a wowhead link for me that I can test with? I tested with https://www.wowhead.com/item=209535/verdant-gladiators-splitter but this works just fine

**Comment by DoctorKohn** [comment]
Not OP, but I'm encountering the same behavior.  You can reproduce it by announcing any piece of upgradable loot on any upgrade track.  The announcement link will always be the base item with no upgrade track attached, which for 10.2 raid pieces will always be 441.  For example, if I announce this:
![image](https://github.com/papa-smurf/Gargul/assets/6538135/1eadac55-5d87-4d2e-876c-824d0f09ac5b)

the link in chat shows
![image](https://github.com/papa-smurf/Gargul/assets/6538135/5642d865-5596-449e-b466-d104b724687f)

**Comment by Tindrith** [comment]
![image](https://github.com/papa-smurf/Gargul/assets/7447192/2ace0360-0a8b-43a8-86e5-50da17dadcde)

That's the way it looks for every item on mouseover of the link.

**Comment by papa-smurf** [comment]
@Tindrith / @DoctorKohn can you try again after updating to v7.2.6 (building currently)? I couldn't find the relevant itemlinks so I couldn't test it properly

**Comment by DoctorKohn** [comment]
I just tested with v7.2.7 in raid tonight and item links were matching the announced items.  Thank you!

**Comment by Tindrith** [comment]
Yeah, had my first raid tonight after the update. It works, thank you.
